### ISSUE TITLE
package install error on 4.6.1 web application

### ISSUE THREAD

**Issue by andreyshiryaev** [rocklan/prometheus-net.AspNet#3]
Hi 

I have old asp.net solution with framework 4.6.1 and i can't install prometheus-net.AspNet

![image](https://user-images.githubusercontent.com/14107563/97988448-ad787100-1de5-11eb-99ce-7fd278ecee1f.png)

**Comment by rocklan** [comment]
I think you need 4.7.1, can you try upgrading your project to that? I think 4.6.1 is out of date and has security holes.
