### ISSUE TITLE
PrometheusHttpRequestModule on OWIN application

### ISSUE THREAD

**Issue by renoojohn** [rocklan/prometheus-net.AspNet#4]
How do we initialize PrometheusHttpRequestModule when the webapp is using OWIN?  Owin app has Startup file and doesnt have a Global.asax file to initialize the HTTP module

@rocklan

**Comment by vaibhav00018** [comment]
@renoojohn any update on this issue. try to add this package on self-hosted console application, but not able to get the http metrics.

**Comment by rocklan** [comment]
@vaibhav00018 for a self-hosted console app that uses OWIN, you can just put the following line inside the `Startup.Configuration` method:

```
PrometheusConfig.UseMetricsServer(config, "metrics");
```

This worked for me after I created a test app using this guide - https://docs.microsoft.com/en-us/aspnet/web-api/overview/hosting-aspnet-web-api/use-owin-to-self-host-web-api

**Comment by rocklan** [comment]
@renoojohn are you talking about a console app that uses OWIN or an ASP.NET app?

**Comment by renoojohn** [comment]
@rocklan . I am using a ASP.NET web Api using Owin.

**Comment by rocklan** [comment]
@renoojohn I've got it to work. Add two nuget packages: 

- Microsoft.Owin.Host.SystemWeb
- Microsoft.AspNet.WebApi.Owin

Then change your startup to look something like this:

```
[assembly: OwinStartup(typeof(WebApplication1.Startup))]
namespace WebApplication1
{
    public class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            HttpConfiguration httpConfiguration = new HttpConfiguration();
            WebApiConfig.Register(httpConfiguration);
            app.UseWebApi(httpConfiguration);
        }
    }

    public class WebApiConfig
    {
        public static void Register(HttpConfiguration config)
        {
            // add your normal routing here
            config.Routes.MapHttpRoute( ... );

            // register metrics endpoint:
            PrometheusConfig.UseMetricsServer(config, "metrics");
        }
    }
}
```
