### ISSUE TITLE
Possible to cleanly apply custom AuthorizeAttribute to PrometheusMetricsController?

### ISSUE THREAD

**Issue by Waddlen** [rocklan/prometheus-net.AspNet#6]
I want to protect the `/metrics` endpoint with my own auth attribute.
```
public class MyAuthAttribute : AuthorizeAttribute
{
    public override void OnAuthorization(HttpActionContext actionContext)
    {
        ... // stuff here
    }
}
```
However, I'm not sure how to cleanly apply this to `PrometheusMetricsController`. The cleanest I could come up with was inheriting it & applying it to the child:
```
[MyAuth]
public class TestController : PrometheusMetricsController
{
}
```
Then replacing the `WebApiConfig.cs` line 
`PrometheusConfig.UseMetricsServer(config, "metrics");`
with
`config.Routes.MapHttpRoute("Prometheus", "metrics", new { controller = "Test" });`

Do you have any better ideas?

Thank you.

**Comment by rocklan** [comment]
Looks like a great solution to me. Great job!

**Comment by rocklan** [comment]
If you are implementing oAuth or something similar, consider creating a PR so that others can use it too :)
